import os

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN", "")
DATABASE_PATH = os.getenv("DATABASE_PATH", "rpg_bot.db")
BOT_PREFIX = "!"
INITIAL_GOLD = 100
MAX_LEVEL = 100
XP_BASE = 100
XP_GROWTH = 1.5
POINTS_PER_LEVEL = 3
MAX_INVENTORY_SIZE = 30
